export const GETDATAFOOTER = "GETDATAFOOTER";
export const ADDDATAFOOTER = "ADDDATAFOOTER";
export const EDITDATAFOOTER = "EDITDATAFOOTER";
export const DELETEDATAFOOTER = "DELETEDATAFOOTER";
export const UPLOADLOGOFOOTER = "UPLOADLOGOFOOTER";