export const GETDATACATEGORIES = "GETDATACATEGORIES";
export const ADDDATACATEGORIES = "ADDDATACATEGORIES";
export const EDITDATACATEGORIES = "EDITDATACATEGORIES";
export const DELETEDATACATEGORIES = "DELETEDATACATEGORIES";