export const GETDATASLIDESHOW = "GETDATASLIDESHOW";
export const ADDDATASLIDESHOW = "ADDDATASLIDESHOW";
export const EDITDATASLIDESHOW = "EDITDATASLIDESHOW";
export const DELETEDATASLIDESHOW = "DELETEDATASLIDESHOW";
export const UPLOAD = "UPLOAD";