export const GETDATAPRODUCT = "GETDATAPRODUCT";
export const ADDDATAPRODUCT = "ADDDATAPRODUCT";
export const EDITDATAPRODUCT = "EDITDATAPRODUCT";
export const DELETEDATAPRODUCT = "DELETEDATAPRODUCT";
export const UPLOADPRODUCT = "UPLOADPRODUCT";
export const ADDCOLOR = "ADDCOLOR";
export const ADDSIZE = "ADDSIZE";