export const GETDATABLOG = "GETDATABLOG";
export const ADDDATABLOG = "ADDDATABLOG";
export const EDITDATABLOG = "EDITDATABLOG";
export const DELETEDATABLOG = "DELETEDATABLOG";
export const UPLOADIMAGEBLOG = "UPLOADIMAGEBLOG";