export const GETUSERADMIN = "GETUSERADMIN";
export const GETMESSAGE = "GETMESSAGE";
export const TOGGLEMESSAGE = "TOGGLEMESSAGE";
export const GETMESSAGEADMIN = "GETMESSAGEADMIN";
export const GETUSERCUSTOMER = "GETUSERCUSTOMER";